# Site settings
title: Cyclehack Twin Cities
email: cyclehacktc@zzolo.org
description: In June, 2015 Cyclehack Twin Cities will bring the Cyclehack Global Movement to Minneapolis for a two-day community event, June 19th and 20th.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cyclehacktc.com" # the base hostname & protocol for your site
twitter_username: zzolo
github_username: cyclehacktc
facebook_group: cyclehacktc
social_image: "/images/logo-circle.png"
timezone: "America/Chicago"
locale: en_us

# Build settings
markdown: kramdown

exclude: [vendor, vender]
